name: Build
on: [ push ]

env:
  GODOT_VERSION: 4.3-dev5
  EXPORT_NAME: ludum-dare-55

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd ./godot
          output=$(godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64)
          echo "$output" | grep "with error"
          if [ $? -eq 0 ]; then
            echo "Error detected"
            exit 1
          fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux